//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Dino_ljaic_lab7_C3.net.azurewebsites.lab7dms {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicesMultiplatformSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WebServicesMultiplatform : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback debugTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLanguagesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddWordOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllWordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogInOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNativeLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLearningLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback createMultipleRandomQuizesOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOneQuizOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStudentQuizesOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitQuizAnswerOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitGradeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGradeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServicesMultiplatform() {
            this.Url = global::Dino_ljaic_lab7_C3.Properties.Settings.Default.Dino_ljaic_lab7_C3_net_azurewebsites_lab7dms_WebServicesMultiplatform;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event debugTestCompletedEventHandler debugTestCompleted;
        
        /// <remarks/>
        public event GetLanguagesListCompletedEventHandler GetLanguagesListCompleted;
        
        /// <remarks/>
        public event AddWordCompletedEventHandler AddWordCompleted;
        
        /// <remarks/>
        public event AddLanguageCompletedEventHandler AddLanguageCompleted;
        
        /// <remarks/>
        public event GetAllWordsCompletedEventHandler GetAllWordsCompleted;
        
        /// <remarks/>
        public event RegisterStudentCompletedEventHandler RegisterStudentCompleted;
        
        /// <remarks/>
        public event GetAllUsersCompletedEventHandler GetAllUsersCompleted;
        
        /// <remarks/>
        public event LogInCompletedEventHandler LogInCompleted;
        
        /// <remarks/>
        public event getNativeLanguageCompletedEventHandler getNativeLanguageCompleted;
        
        /// <remarks/>
        public event getLearningLanguageCompletedEventHandler getLearningLanguageCompleted;
        
        /// <remarks/>
        public event createMultipleRandomQuizesCompletedEventHandler createMultipleRandomQuizesCompleted;
        
        /// <remarks/>
        public event createOneQuizCompletedEventHandler createOneQuizCompleted;
        
        /// <remarks/>
        public event getStudentQuizesCompletedEventHandler getStudentQuizesCompleted;
        
        /// <remarks/>
        public event submitQuizAnswerCompletedEventHandler submitQuizAnswerCompleted;
        
        /// <remarks/>
        public event submitGradeCompletedEventHandler submitGradeCompleted;
        
        /// <remarks/>
        public event getGradeCompletedEventHandler getGradeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/debugTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string debugTest() {
            object[] results = this.Invoke("debugTest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void debugTestAsync() {
            this.debugTestAsync(null);
        }
        
        /// <remarks/>
        public void debugTestAsync(object userState) {
            if ((this.debugTestOperationCompleted == null)) {
                this.debugTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OndebugTestOperationCompleted);
            }
            this.InvokeAsync("debugTest", new object[0], this.debugTestOperationCompleted, userState);
        }
        
        private void OndebugTestOperationCompleted(object arg) {
            if ((this.debugTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.debugTestCompleted(this, new debugTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLanguagesList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetLanguagesList() {
            object[] results = this.Invoke("GetLanguagesList", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLanguagesListAsync() {
            this.GetLanguagesListAsync(null);
        }
        
        /// <remarks/>
        public void GetLanguagesListAsync(object userState) {
            if ((this.GetLanguagesListOperationCompleted == null)) {
                this.GetLanguagesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLanguagesListOperationCompleted);
            }
            this.InvokeAsync("GetLanguagesList", new object[0], this.GetLanguagesListOperationCompleted, userState);
        }
        
        private void OnGetLanguagesListOperationCompleted(object arg) {
            if ((this.GetLanguagesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLanguagesListCompleted(this, new GetLanguagesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddWord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddWord(string lang, string word) {
            object[] results = this.Invoke("AddWord", new object[] {
                        lang,
                        word});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddWordAsync(string lang, string word) {
            this.AddWordAsync(lang, word, null);
        }
        
        /// <remarks/>
        public void AddWordAsync(string lang, string word, object userState) {
            if ((this.AddWordOperationCompleted == null)) {
                this.AddWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddWordOperationCompleted);
            }
            this.InvokeAsync("AddWord", new object[] {
                        lang,
                        word}, this.AddWordOperationCompleted, userState);
        }
        
        private void OnAddWordOperationCompleted(object arg) {
            if ((this.AddWordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddWordCompleted(this, new AddWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddLanguage(string lang) {
            object[] results = this.Invoke("AddLanguage", new object[] {
                        lang});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddLanguageAsync(string lang) {
            this.AddLanguageAsync(lang, null);
        }
        
        /// <remarks/>
        public void AddLanguageAsync(string lang, object userState) {
            if ((this.AddLanguageOperationCompleted == null)) {
                this.AddLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddLanguageOperationCompleted);
            }
            this.InvokeAsync("AddLanguage", new object[] {
                        lang}, this.AddLanguageOperationCompleted, userState);
        }
        
        private void OnAddLanguageOperationCompleted(object arg) {
            if ((this.AddLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddLanguageCompleted(this, new AddLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllWords", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetAllWords(string lang) {
            object[] results = this.Invoke("GetAllWords", new object[] {
                        lang});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllWordsAsync(string lang) {
            this.GetAllWordsAsync(lang, null);
        }
        
        /// <remarks/>
        public void GetAllWordsAsync(string lang, object userState) {
            if ((this.GetAllWordsOperationCompleted == null)) {
                this.GetAllWordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllWordsOperationCompleted);
            }
            this.InvokeAsync("GetAllWords", new object[] {
                        lang}, this.GetAllWordsOperationCompleted, userState);
        }
        
        private void OnGetAllWordsOperationCompleted(object arg) {
            if ((this.GetAllWordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllWordsCompleted(this, new GetAllWordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegisterStudent(string name, string surname, string lang_native, string lang_learning) {
            object[] results = this.Invoke("RegisterStudent", new object[] {
                        name,
                        surname,
                        lang_native,
                        lang_learning});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterStudentAsync(string name, string surname, string lang_native, string lang_learning) {
            this.RegisterStudentAsync(name, surname, lang_native, lang_learning, null);
        }
        
        /// <remarks/>
        public void RegisterStudentAsync(string name, string surname, string lang_native, string lang_learning, object userState) {
            if ((this.RegisterStudentOperationCompleted == null)) {
                this.RegisterStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterStudentOperationCompleted);
            }
            this.InvokeAsync("RegisterStudent", new object[] {
                        name,
                        surname,
                        lang_native,
                        lang_learning}, this.RegisterStudentOperationCompleted, userState);
        }
        
        private void OnRegisterStudentOperationCompleted(object arg) {
            if ((this.RegisterStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterStudentCompleted(this, new RegisterStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetAllUsers() {
            object[] results = this.Invoke("GetAllUsers", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUsersAsync() {
            this.GetAllUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllUsersAsync(object userState) {
            if ((this.GetAllUsersOperationCompleted == null)) {
                this.GetAllUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUsersOperationCompleted);
            }
            this.InvokeAsync("GetAllUsers", new object[0], this.GetAllUsersOperationCompleted, userState);
        }
        
        private void OnGetAllUsersOperationCompleted(object arg) {
            if ((this.GetAllUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUsersCompleted(this, new GetAllUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LogIn(string username) {
            object[] results = this.Invoke("LogIn", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LogInAsync(string username) {
            this.LogInAsync(username, null);
        }
        
        /// <remarks/>
        public void LogInAsync(string username, object userState) {
            if ((this.LogInOperationCompleted == null)) {
                this.LogInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogInOperationCompleted);
            }
            this.InvokeAsync("LogIn", new object[] {
                        username}, this.LogInOperationCompleted, userState);
        }
        
        private void OnLogInOperationCompleted(object arg) {
            if ((this.LogInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogInCompleted(this, new LogInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNativeLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNativeLanguage(string username) {
            object[] results = this.Invoke("getNativeLanguage", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNativeLanguageAsync(string username) {
            this.getNativeLanguageAsync(username, null);
        }
        
        /// <remarks/>
        public void getNativeLanguageAsync(string username, object userState) {
            if ((this.getNativeLanguageOperationCompleted == null)) {
                this.getNativeLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNativeLanguageOperationCompleted);
            }
            this.InvokeAsync("getNativeLanguage", new object[] {
                        username}, this.getNativeLanguageOperationCompleted, userState);
        }
        
        private void OngetNativeLanguageOperationCompleted(object arg) {
            if ((this.getNativeLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNativeLanguageCompleted(this, new getNativeLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLearningLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLearningLanguage(string username) {
            object[] results = this.Invoke("getLearningLanguage", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLearningLanguageAsync(string username) {
            this.getLearningLanguageAsync(username, null);
        }
        
        /// <remarks/>
        public void getLearningLanguageAsync(string username, object userState) {
            if ((this.getLearningLanguageOperationCompleted == null)) {
                this.getLearningLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLearningLanguageOperationCompleted);
            }
            this.InvokeAsync("getLearningLanguage", new object[] {
                        username}, this.getLearningLanguageOperationCompleted, userState);
        }
        
        private void OngetLearningLanguageOperationCompleted(object arg) {
            if ((this.getLearningLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLearningLanguageCompleted(this, new getLearningLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createMultipleRandomQuizes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool createMultipleRandomQuizes(int amount, string nativeLang, string username) {
            object[] results = this.Invoke("createMultipleRandomQuizes", new object[] {
                        amount,
                        nativeLang,
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void createMultipleRandomQuizesAsync(int amount, string nativeLang, string username) {
            this.createMultipleRandomQuizesAsync(amount, nativeLang, username, null);
        }
        
        /// <remarks/>
        public void createMultipleRandomQuizesAsync(int amount, string nativeLang, string username, object userState) {
            if ((this.createMultipleRandomQuizesOperationCompleted == null)) {
                this.createMultipleRandomQuizesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateMultipleRandomQuizesOperationCompleted);
            }
            this.InvokeAsync("createMultipleRandomQuizes", new object[] {
                        amount,
                        nativeLang,
                        username}, this.createMultipleRandomQuizesOperationCompleted, userState);
        }
        
        private void OncreateMultipleRandomQuizesOperationCompleted(object arg) {
            if ((this.createMultipleRandomQuizesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createMultipleRandomQuizesCompleted(this, new createMultipleRandomQuizesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createOneQuiz", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool createOneQuiz(string username, string Q_word) {
            object[] results = this.Invoke("createOneQuiz", new object[] {
                        username,
                        Q_word});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void createOneQuizAsync(string username, string Q_word) {
            this.createOneQuizAsync(username, Q_word, null);
        }
        
        /// <remarks/>
        public void createOneQuizAsync(string username, string Q_word, object userState) {
            if ((this.createOneQuizOperationCompleted == null)) {
                this.createOneQuizOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOneQuizOperationCompleted);
            }
            this.InvokeAsync("createOneQuiz", new object[] {
                        username,
                        Q_word}, this.createOneQuizOperationCompleted, userState);
        }
        
        private void OncreateOneQuizOperationCompleted(object arg) {
            if ((this.createOneQuizCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createOneQuizCompleted(this, new createOneQuizCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getStudentQuizes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] getStudentQuizes(string username) {
            object[] results = this.Invoke("getStudentQuizes", new object[] {
                        username});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getStudentQuizesAsync(string username) {
            this.getStudentQuizesAsync(username, null);
        }
        
        /// <remarks/>
        public void getStudentQuizesAsync(string username, object userState) {
            if ((this.getStudentQuizesOperationCompleted == null)) {
                this.getStudentQuizesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStudentQuizesOperationCompleted);
            }
            this.InvokeAsync("getStudentQuizes", new object[] {
                        username}, this.getStudentQuizesOperationCompleted, userState);
        }
        
        private void OngetStudentQuizesOperationCompleted(object arg) {
            if ((this.getStudentQuizesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStudentQuizesCompleted(this, new getStudentQuizesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/submitQuizAnswer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool submitQuizAnswer(int id, string asnwer) {
            object[] results = this.Invoke("submitQuizAnswer", new object[] {
                        id,
                        asnwer});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void submitQuizAnswerAsync(int id, string asnwer) {
            this.submitQuizAnswerAsync(id, asnwer, null);
        }
        
        /// <remarks/>
        public void submitQuizAnswerAsync(int id, string asnwer, object userState) {
            if ((this.submitQuizAnswerOperationCompleted == null)) {
                this.submitQuizAnswerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitQuizAnswerOperationCompleted);
            }
            this.InvokeAsync("submitQuizAnswer", new object[] {
                        id,
                        asnwer}, this.submitQuizAnswerOperationCompleted, userState);
        }
        
        private void OnsubmitQuizAnswerOperationCompleted(object arg) {
            if ((this.submitQuizAnswerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitQuizAnswerCompleted(this, new submitQuizAnswerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/submitGrade", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool submitGrade(string username, string grade) {
            object[] results = this.Invoke("submitGrade", new object[] {
                        username,
                        grade});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void submitGradeAsync(string username, string grade) {
            this.submitGradeAsync(username, grade, null);
        }
        
        /// <remarks/>
        public void submitGradeAsync(string username, string grade, object userState) {
            if ((this.submitGradeOperationCompleted == null)) {
                this.submitGradeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitGradeOperationCompleted);
            }
            this.InvokeAsync("submitGrade", new object[] {
                        username,
                        grade}, this.submitGradeOperationCompleted, userState);
        }
        
        private void OnsubmitGradeOperationCompleted(object arg) {
            if ((this.submitGradeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitGradeCompleted(this, new submitGradeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getGrade", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getGrade(string username) {
            object[] results = this.Invoke("getGrade", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGradeAsync(string username) {
            this.getGradeAsync(username, null);
        }
        
        /// <remarks/>
        public void getGradeAsync(string username, object userState) {
            if ((this.getGradeOperationCompleted == null)) {
                this.getGradeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGradeOperationCompleted);
            }
            this.InvokeAsync("getGrade", new object[] {
                        username}, this.getGradeOperationCompleted, userState);
        }
        
        private void OngetGradeOperationCompleted(object arg) {
            if ((this.getGradeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGradeCompleted(this, new getGradeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void debugTestCompletedEventHandler(object sender, debugTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class debugTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal debugTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetLanguagesListCompletedEventHandler(object sender, GetLanguagesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLanguagesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLanguagesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddWordCompletedEventHandler(object sender, AddWordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddLanguageCompletedEventHandler(object sender, AddLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllWordsCompletedEventHandler(object sender, GetAllWordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RegisterStudentCompletedEventHandler(object sender, RegisterStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllUsersCompletedEventHandler(object sender, GetAllUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LogInCompletedEventHandler(object sender, LogInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getNativeLanguageCompletedEventHandler(object sender, getNativeLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNativeLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNativeLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getLearningLanguageCompletedEventHandler(object sender, getLearningLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLearningLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLearningLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void createMultipleRandomQuizesCompletedEventHandler(object sender, createMultipleRandomQuizesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createMultipleRandomQuizesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createMultipleRandomQuizesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void createOneQuizCompletedEventHandler(object sender, createOneQuizCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createOneQuizCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createOneQuizCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getStudentQuizesCompletedEventHandler(object sender, getStudentQuizesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStudentQuizesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStudentQuizesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void submitQuizAnswerCompletedEventHandler(object sender, submitQuizAnswerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitQuizAnswerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitQuizAnswerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void submitGradeCompletedEventHandler(object sender, submitGradeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitGradeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitGradeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getGradeCompletedEventHandler(object sender, getGradeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGradeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGradeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591