//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dino_ljaic_lab7_C3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lab7dms.azurewebsites.net/WebServicesMultiplatform.asmx")]
        public string Dino_ljaic_lab7_C3_net_azurewebsites_lab7dms_WebServicesMultiplatform {
            get {
                return ((string)(this["Dino_ljaic_lab7_C3_net_azurewebsites_lab7dms_WebServicesMultiplatform"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lab7mds.azurewebsites.net/WebServicesMultiplatform.asmx")]
        public string Dino_ljaic_lab7_C3_net_azurewebsites_lab7mds_WebServicesMultiplatform {
            get {
                return ((string)(this["Dino_ljaic_lab7_C3_net_azurewebsites_lab7mds_WebServicesMultiplatform"]));
            }
        }
    }
}
